name: Elastic Beanstalk Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Elastic Beanstalk Deployment
      uses: kumarshivam12/Aws-ElasticBeanstalk@v1.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        APPLICATION-NAME: 
          description : CommendaTest
        EB-ENV-NAME: 
          description : CommendaTest-env
        AWS-REGION: 
          description : ap-south-1 
