name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        uses: kumarshivam12/Aws-ElasticBeanstalk@v1.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APPLICATION-NAME: CommendaTest
          EB-ENV-NAME: CommendaTest-env
          AWS-REGION: ap-south-1
